version: '3'

services:
  nginx:
    image: nginx:latest
#    environment:
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/strapi.conf:/etc/nginx/conf.d/strapi.conf
    links:
      - strapi_api
    restart: always
  strapi_api:
    container_name: jenkins.marguerite.io
    image: jenkins:2.60.3
    build:
      context: ./construction/strapi
#       args:
#         - MARGUERITE_HOST=jenkins.marguerite.io
#  docker run --name myjenkins -p 8080:8080 -p 50000:50000 --env JAVA_OPTS=-Dhudson.footerURL=http://mycompany.com jenkins
    environment:
      - JAVA_OPTS=-Dhudson.footerURL=http://mycompany.com jenkins
      # à tester : passer plusieurs JAVA_OPTS au démarrage de Jenkins, en mettant la valeur de JAVA_OPTS entre guillemets  
      # - JAVA_OPTS="-Dhudson.footerURL=http://mycompany.com jenkins  -Dune.autre.option.jenkins=savaleur    "
      # - MARGUERITE_HOST=jenkins.marguerite.io
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./marguerite:/var/jenkins_home jenkins
      # - /usr/src/api/instance-strapi/node_modules
#     depends_on:
#       - strapibdd
    restart: always

