version: '3'

services:
  nginx:
    image: nginx:latest
#    environment:
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/strapi.conf:/etc/nginx/conf.d/strapi.conf
    links:
      - strapi_api 
    restart: always
  strapi_api:
    image: carrefour/strapi:1.0.0
    build:
      context: ./construction/strapi
      args:
        - APP_NAME_PAR_DEFAUT=jbl-strapi
        - DATABASE_CLIENT_PAR_DEFAUT=mongo
        - DATABASE_HOST_PAR_DEFAUT=initialisation_strapibdd_1
        - DATABASE_PORT_PAR_DEFAUT=27017
        - DATABASE_NAME_PAR_DEFAUT=strapi
        - DATABASE_USERNAME_PAR_DEFAUT=
        - DATABASE_PASSWORD_PAR_DEFAUT=
        # - HOST=localhost
        # Les variables ci-dessous sont utilisées pour les déploiements de code livré par l'équipe de dev
        # - REPERTOIRE_LIVRAISON_DEV_PAR_DEFAUT=/usr/src/api/livraison-dev
        # le répertorie dans lequel on invoque strapi new doit être vide, donc /usr/src/api
        - REPERTOIRE_LIVRAISON_DEV=/usr/src/livraison-dev

    environment:
      - APP_NAME=jbl-strapi
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=initialisation_strapibdd_1
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      # - HOST=localhost
      # Les variables ci-dessous sont utilisées pour les déploiements de code livré par l'équipe de dev
      - REPERTOIRE_LIVRAISON_DEV=/usr/src/livraison-dev

    ports:
      - 1337:1337
#    volumes:
      # - ./instance-strapi:/usr/src/api/instance-strapi
      # - /usr/src/api/instance-strapi/node_modules
    depends_on:
      - strapibdd
    restart: always

  strapibdd:
    image: mongo
#    hostname: strapibdd_1
    environment:
      - MONGO_INITDB_DATABASE=strapi
    ports:
      - 27017:27017
    volumes:
      - ./strapibdd:/data/db
    restart: always
